---
kind: pipeline
type: kubernetes
name: default
service_account_name: drone-runner-aws-privileges

steps:
  - name: build ksa
    role_arn_to_assume: 'arn:aws:iam::164490501968:role/prod/gulf/ziwo/k8s_core/drone-runner'
    image: plugins/kaniko-ecr
    environment:
      NEXT_PUBLIC_GOOGLE_ANALYTICS: UA-131299981-1
    resources:
      limits:
        cpu: 2000
        memory: 4096MiB
    settings:
      registry: 164490501968.dkr.ecr.me-south-1.amazonaws.com
      repo: ksa-website
      tags:
        - ${DRONE_COMMIT_SHA}
        - latest
    when:
      branch:
        - master
  - name: update IaC
    image: minghsu0107/update-kustomization
    environment:
      SSH_KEY:
        from_secret: github-ssh
      MANIFEST_HOST: github.com
      MANIFEST_USER: ASWATFZLLC
      MANIFEST_REPO: infra-k8s-deployments
      MANIFEST_BRANCH: master
      IMAGES: 164490501968.dkr.ecr.me-south-1.amazonaws.com/ksa-website
      IMAGE_TAG: ${DRONE_COMMIT_SHA}
      KUSTOMIZATION: marketing/ksa-landing-page/production
